const fs = require('node:fs');
const rules = {};
const open = ['commuters','ambassador_team_chat','taxis','requests','notifications','chats','subscriptions','withdrawals','voucherUsage','businessUsers_PLACEHOLDER','admins','debitOrderQueue','debitOrders','marketAds','verificationQueue','support_chats','driver_applications'];
open.filter(k => !k.includes('PLACEHOLDER')).forEach(k => rules[k] = {'.read':true,'.write':true});
const authenticated = ['vouchers','voucher_requests','businesses','settings','delivery_requests','pending_deliveries','payout_requests','earnings','campuses'];
authenticated.forEach(k => rules[k] = {'.read':'auth != null','.write':'auth != null'});
const own = {'.read':'auth != null && auth.uid === $uid','.write':'auth != null && auth.uid === $uid'};
rules.users = {'.indexOn':['email'],'.read':"auth != null && root.child('admins').hasChild(auth.uid)",'$uid':own};
rules.businessUsers = {'$uid':own}; rules.campaigns = {'$uid':own};
rules.club_pools = {'.read':"auth != null && root.child('admins').child(auth.uid).exists()",'.write':"auth != null && root.child('admins').child(auth.uid).exists()",waiting_list:{'.read':'auth != null','$uid':{'.write':'auth != null'}}};
rules.adAnalytics = {'.read':'auth != null','.write':"auth != null && auth.uid === 'YOUR_ADMIN_UID_HERE'"};
rules.messages = {'$uid':{'.read':'auth != null && auth.uid === $uid','.write':'auth != null'}};
rules.handlers = {'.indexOn':['phone','email'],'.read':true,'.write':'auth != null'};
rules.admin_queue = {'.read':'auth != null','.write':'auth != null',external_vouchers:{'.indexOn':['status']}};
rules.handler_applications = {'.read':'auth != null','$application_id':{'.write':'!data.exists()'}};
rules.drivers = {'.indexOn':['email','phone','licenseNumber','status'],'.read':'auth != null','$uid':{'.read':'auth != null','.write':"auth != null && (auth.uid === $uid || root.child('admins').hasChild(auth.uid))"}};
rules.adRewards = {'$uid':{'.write':'$uid === auth.uid','.read':'$uid === auth.uid'}};
const indexes = {commuters:['phone','isAmbassador','verificationStatus'],taxis:['phone','isOnline','destination'],requests:['taxiId','status','commuterId','timestamp'],vouchers:'code',voucher_requests:['ambassadorPhone'],marketAds:['userId','status','createdAt'],delivery_requests:['commuterId','handlerId','status','assignedTaxiId'],pending_deliveries:['orderId','createdAt'],payout_requests:['status','requestedAt'],earnings:['handlerId','timestamp'],driver_applications:['email','phone']};
for (const [key,value] of Object.entries(indexes)) rules[key]['.indexOn']=value;
rules.tripChats = JSON.parse(fs.readFileSync('test/trip-chat.rules.fragment.json','utf8')).rules.tripChats;
fs.writeFileSync('test/firebase.rules.merged.json',JSON.stringify({rules},null,2)+'\n');
