name: iOS TestFlight Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout App Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # FIX 1: We DO need a working directory because the code is inside the asiye_app folder!
      - name: Install Flutter Dependencies
        working-directory: ./asiye_app
        run: flutter pub get

      - name: Build and Upload to TestFlight 
        working-directory: ./asiye_app/ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: fastlane beta
